name: vilaexplorer
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  http: ^1.2.2
  image_picker: ^1.1.2
  flutter_screenutil: ^5.9.3
  geolocator: ^13.0.2
  flutter_dotenv: ^5.2.1
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.8.0
  icons_plus: ^5.0.0
  collection: ^1.18.0
  path_provider: ^2.1.5
  flutter_map_tile_caching: ^10.0.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/VilaExplorer.png"
  min_sdk_android: 21
  adaptive_icon_background: "#202020" 
  adaptive_icon_foreground: "assets/images/VilaExplorer.png"
  adaptive_icon_foreground_inset: 25 
  web: 
    generate: true
    image_path: "assets/images/VilaExplorer.png"
    background_color: "#202020"
    theme_color: "#202020"
  windows:
    generate: true
    image_path: "assets/images/VilaExplorer.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/VilaExplorer.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - lib/icon/
    - assets/
    - assets/images_gastronomia/
    - assets/images_historias/
    - assets/historias.json
    - assets/lang/
    - assets/no-image.jpg
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
